
version: 2

models:
    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: true_class
            description: "its a country"
            tests:
                - not_null
          - name: pred_class
            description: "bro who cares"
            tests:
                - not_null
          - name: pred_proba
            description: "bro who cares"
            tests:
                - not_null
          - name: run_timestamp
            description: "bro who cares"
            tests:
                - not_null



##    - name: my_second_dbt_model
##      description: "A starter dbt model"
##     columns:
##          - name: id
##           description: "The primary key for this table"
##            tests:
##                - unique
##                - not_null
