version: 2

sources:
  - name: globalhealthdatascience  # this is the logical name you'll use in `source()`
    schema: globalhealthdatascience  # this is the BigQuery dataset name
    tables:
      - name: world_bank_data  # this is the actual table name
